version: '3'
services:
  top.api:
    image: docker.pkg.github.com/yavchikalov/top-api-back/top-api-back:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env